### PR TITLE
components set up

### PR DESCRIPTION
**Pull request by Diane-Sayos**
break down of components and views // tidying up the application

### CODE REVIEW

**Comment by bob-zs** [comment]
Awesome!!!!!!!

**Comment by bob-zs** [comment]
This looks great, let's merge this

**Review by bob-zs — APPROVED** [review]

**Comment by alejandro-loja** [comment]
cool

**Review by Banychen — APPROVED** [review]
Chloe

**Review by alejandro-loja — APPROVED** [review]
ok

**Pull request merged**
